baseURL = 'http://codesolid.com'
languageCode = 'en-us'
title = 'CodeSolid'
theme = 'hugo-theme-stack'

[permalinks]
	posts = "/:filename/"

sectionPagesMenu = "main"
[menu]
[[menu.main]]
	name = "Blog"
	url = "/blog"
	weight = 1

[[menu.main]]
	name = "Online Python"
	url = "https://jupyter.codesolid.com/lab/index.html"
	weight = 5
	[menu.main.params]
        newTab = true
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/CodeSolid"
	weight = 10
    [menu.main.params]
        #icon = "Github"
        newTab = true

[Params]
# mainSections = ["posts", "math", "about"	] # Specify section pages to show on home page and the "Recent articles" widget
#toc = true # Enable Table of Contents

[Params.Sidebar]
avatar.src = "/images/logo150.png"
avatar.local = false


